### ISSUE TITLE
Replace the object specific confidence values in detector/classifiers with a single default value

### ISSUE THREAD

**Issue by hooman67** [auperatech/VMSS2.0_Documentation#19] opened 2023-02-21 21:48 UTC

**Comment by LCY02** [comment] 2023-03-21 23:42
Duplicate of https://github.com/auperatech/VMSS2.0_Documentation/issues/17. Has been completed in https://github.com/auperatech/VMSS2.0_Documentation/pull/16

**Closed by LCY02** 2023-03-21 23:42 UTC
